# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57b5494a7edee8266ecbdabef6b0e1a5226720133b9f3cec9fab801c3e12034fa22b2f113a27fe7430e871b5530f8ef834e8719ab41d2a217b484f91861a32c8

test:
  secret_key_base: 082e4dbf76561c4dee03996791726e132d3d4d86c129ab3dc57d8b0199573a0fcb3d4b3c9b404468ab7fe638a5b7164c82db10ef47efb2196bd4a7e24bbfd420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
